language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

sudo: false

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer install --no-interaction

script: vendor/bin/phpunit
